### ISSUE TITLE
eglinfo segfault at device #1

### ISSUE THREAD

**Issue by AngelBePro** [NVIDIA/egl-wayland#158]
System specs:

Operating System: Arch Linux 
KDE Plasma Version: 6.2.4
KDE Frameworks Version: 6.8.0
Qt Version: 6.8.1
Kernel Version: 6.12.4-arch1-1 (64-bit)
Graphics Platform: Wayland
Processors: 12 × Intel® Core™ i5-10400F CPU @ 2.90GHz
Memory: 15,5 GiB of RAM
Graphics Processor: NVIDIA GeForce RTX 3070/PCIe/SSE2
Manufacturer: Micro-Star International Co., Ltd.
Product Name: MS-7D15
System Version: 3.0

Running eglinfo just segfault at Device #1. I don't have a second gpu if that's for some reason what device #1 is supposed to be. I tested using nouveau drivers and issue isn't there. Here is a log https://0x0.st/XFX8.txt.

**Comment by amshafer** [comment]
What in egl-wayland is causing issues for you? Do you see the crash in egl-wayland? I can reproduce but see the NVIDIA device getting printed correctly.

The segfault looks to be in mesa:
```
Program received signal SIGSEGV, Segmentation fault.
0x00007fffe023d12f in ?? () from /usr/lib/libgallium-24.3.0-arch1.1.so
(gdb) bt
#0  0x00007fffe023d12f in ?? () from /usr/lib/libgallium-24.3.0-arch1.1.so
#1  0x00007fffe02382f6 in driCreateNewScreen3 () from /usr/lib/libgallium-24.3.0-arch1.1.so
#2  0x00007ffff6e88cea in ?? () from /usr/lib/libEGL_mesa.so.0
#3  0x00007ffff6e8a556 in ?? () from /usr/lib/libEGL_mesa.so.0
#4  0x00007ffff6e895b9 in ?? () from /usr/lib/libEGL_mesa.so.0
#5  0x00007ffff6e7797a in ?? () from /usr/lib/libEGL_mesa.so.0
#6  0x00007ffff7c0d854 in eglInitialize (dpy=0x5555559c2700, major=0x7fffffffdd54, minor=0x7fffffffdd50)
    at /nv/git/bfm/drivers/unix/libglvnd/src/EGL/g_egldispatchstubs.c:231
#7  0x000055555555d1cd in doOneDisplay (d=0x5555559c2700, name=name@entry=0x5555555795a5 "Platform Device", opts=...)
    at ../mesa-demos-9.0.0/src/egl/opengl/eglinfo.c:529
#8  0x0000555555555704 in doOneDevice (d=0x5555557660b0, i=<optimized out>, opts=...) at ../mesa-demos-9.0.0/src/egl/opengl/eglinfo.c:647
#9  doDevices (name=0x555555579551 "Device platform", opts=...) at ../mesa-demos-9.0.0/src/egl/opengl/eglinfo.c:673
#10 main (argc=<optimized out>, argv=<optimized out>) at ../mesa-demos-9.0.0/src/egl/opengl/eglinfo.c:859
```

**Comment by AngelBePro** [comment]
```
(gdb) bt
#0  drisw_init_screen () at ../mesa-24.3.1/src/gallium/frontends/dri/drisw.c:623
#1  0x00007fffef438336 in driCreateNewScreen3 () at ../mesa-24.3.1/src/gallium/frontends/dri/dri_util.c:144
#2  0x00007ffff579ecea in dri2_create_screen () at ../mesa-24.3.1/src/egl/drivers/dri2/egl_dri2.c:825
#3  0x00007ffff57a0556 in dri2_initialize_device () at ../mesa-24.3.1/src/egl/drivers/dri2/platform_device.c:362
#4  0x00007ffff579f5b9 in dri2_initialize () at ../mesa-24.3.1/src/egl/drivers/dri2/egl_dri2.c:912
#5  0x00007ffff578d97a in eglInitialize () at ../mesa-24.3.1/src/egl/main/eglapi.c:719
#6  0x000055555555d1cd in doOneDisplay (d=0x55555598ca80, name=name@entry=0x5555555795a5 "Platform Device", opts=...) at ../mesa-demos-9.0.0/src/egl/opengl/eglinfo.c:529
#7  0x0000555555555704 in doOneDevice (d=0x5555559b7710, i=<optimized out>, opts=...) at ../mesa-demos-9.0.0/src/egl/opengl/eglinfo.c:647
#8  doDevices (name=0x555555579551 "Device platform", opts=...) at ../mesa-demos-9.0.0/src/egl/opengl/eglinfo.c:673
#9  main (argc=<optimized out>, argv=<optimized out>) at ../mesa-demos-9.0.0/src/egl/opengl/eglinfo.c:859
```

Should I report this to mesa instead?

**Comment by amshafer** [comment]
Yes I believe that would be the right move
